replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.51.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector:
  kubernetes.io/hostname: software-design-devops-test-vm

serviceAccount:
  create: true
  name: prometheus

ingress:
  enabled: ture
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: prometheus.xn--299a9h35r4sn3oar46g.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prometheus-tls
      hosts:
        - prometheus.xn--299a9h35r4sn3oar46g.site