replicaCount: 1

image:
  repository: quay.io/prometheus/node-exporter
  tag: v1.7.0
  pullPolicy: IfNotPresent

resources: {}

nodeSelector:
  kubernetes.io/hostname: software-design-devops-test-vm

podLabels:
  job: node-exporter  # ← Grafana에서 쉽게 조회되도록

service:
  type: ClusterIP
  port: 9100
  portName: metrics

serviceMonitor:
  enabled: true
  interval: 15s
  additionalLabels:
    release: prometheus
