{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prometheus.xn--299a9h35r4sn3oar46g.site
      secretName: prometheus-tls
  rules:
    - host: prometheus.xn--299a9h35r4sn3oar46g.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "prometheus.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
