replicaCount: 1
image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: monitor.xn--299a9h35r4sn3oar46g.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: monitor-tls
      hosts:
        - monitor.xn--299a9h35r4sn3oar46g.site

adminUser: admin
adminPassword: changeme

nodeSelector:
  kubernetes.io/hostname: software-design-devops-test-vm
