apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-node-exporter
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9100
              name: {{ .Values.service.portName }}
