apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
spec:
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9100
      protocol: TCP
      name: {{ .Values.service.portName }}
  type: {{ .Values.service.type }}
